version: '3'

services:
  db:
    container_name: test-db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=test-db
      - MYSQL_ROOT_PASSWORD=1234
      - TZ=Asia/Seoul
    ports:
      - "13306:3306"
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d